#!/bin/bash
# Get Base Sepolia ETH for deployment

echo "=========================================="
echo "  GET BASE SEPOLIA TEST ETH"
echo "=========================================="
echo ""
echo "Wallet: 0xD8CDe62aCB881329EBb4694f37314b7bBA77EbDe"
echo ""
echo "OPTION 1: Coinbase Faucet (0.05 ETH/day)"
echo "  → https://www.coinbase.com/faucets/base-sepolia-faucet"
echo "  → Login with Coinbase, paste wallet address"
echo ""
echo "OPTION 2: Superchain Faucet (GitHub auth)"
echo "  → https://app.optimism.io/faucet"
echo "  → Connect GitHub, select Base Sepolia"
echo ""
echo "OPTION 3: Alchemy Faucet"
echo "  → https://sepoliafaucet.com/"
echo ""
echo "OPTION 4: QuickNode Faucet"
echo "  → https://faucet.quicknode.com/base/sepolia"
echo ""
echo "After getting funds, run:"
echo "  npx hardhat run scripts/check-balance.js --network baseSepolia"
echo ""
echo "Then deploy:"
echo "  npm run deploy:base-sepolia"
echo "=========================================="
